#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-Moose
Version  : 2.2011
Release  : 4
URL      : https://cpan.metacpan.org/authors/id/E/ET/ETHER/Moose-2.2011.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/E/ET/ETHER/Moose-2.2011.tar.gz
Summary  : 'A postmodern object system for Perl 5'
Group    : Development/Tools
License  : Artistic-1.0-Perl
Requires: perl-Moose-bin = %{version}-%{release}
Requires: perl-Moose-lib = %{version}-%{release}
BuildRequires : buildreq-cpan
BuildRequires : perl(CPAN::Meta::Check)
BuildRequires : perl(Class::Load)
BuildRequires : perl(Class::Load::XS)
BuildRequires : perl(Data::OptList)
BuildRequires : perl(Devel::GlobalDestruction)
BuildRequires : perl(Devel::OverloadInfo)
BuildRequires : perl(Devel::StackTrace)
BuildRequires : perl(Dist::CheckConflicts)
BuildRequires : perl(Eval::Closure)
BuildRequires : perl(MRO::Compat)
BuildRequires : perl(Module::Runtime)
BuildRequires : perl(Module::Runtime::Conflicts)
BuildRequires : perl(Package::DeprecationManager)
BuildRequires : perl(Package::Stash)
BuildRequires : perl(Package::Stash::XS)
BuildRequires : perl(Params::Util)
BuildRequires : perl(Sub::Exporter)
BuildRequires : perl(Sub::Identify)
BuildRequires : perl(Sub::Name)
BuildRequires : perl(Test::CleanNamespaces)
BuildRequires : perl(Test::Fatal)
BuildRequires : perl(Test::Requires)
BuildRequires : perl(Try::Tiny)

%description
[![CPAN version](https://badge.fury.io/pl/Moose.svg)](http://badge.fury.io/pl/Moose)
[![Build Status](https://travis-ci.org/moose/Moose.png?branch=master,stable/2.12)](https://travis-ci.org/moose/Moose)
[![Coverage Status](https://coveralls.io/repos/moose/Moose/badge.png?branch=master)](https://coveralls.io/r/moose/Moose?branch=master)

%package bin
Summary: bin components for the perl-Moose package.
Group: Binaries

%description bin
bin components for the perl-Moose package.


%package dev
Summary: dev components for the perl-Moose package.
Group: Development
Requires: perl-Moose-lib = %{version}-%{release}
Requires: perl-Moose-bin = %{version}-%{release}
Provides: perl-Moose-devel = %{version}-%{release}

%description dev
dev components for the perl-Moose package.


%package lib
Summary: lib components for the perl-Moose package.
Group: Libraries

%description lib
lib components for the perl-Moose package.


%prep
%setup -q -n Moose-2.2011

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%install
rm -rf %{buildroot}
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot} INSTALLDIRS=vendor
else
./Build install --installdirs=vendor --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Class/MOP.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Class/MOP/Attribute.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Class/MOP/Class.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Class/MOP/Class/Immutable/Trait.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Class/MOP/Deprecated.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Class/MOP/Instance.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Class/MOP/Method.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Class/MOP/Method/Accessor.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Class/MOP/Method/Constructor.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Class/MOP/Method/Generated.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Class/MOP/Method/Inlined.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Class/MOP/Method/Meta.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Class/MOP/Method/Wrapped.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Class/MOP/MiniTrait.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Class/MOP/Mixin.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Class/MOP/Mixin/AttributeCore.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Class/MOP/Mixin/HasAttributes.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Class/MOP/Mixin/HasMethods.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Class/MOP/Mixin/HasOverloads.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Class/MOP/Module.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Class/MOP/Object.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Class/MOP/Overload.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Class/MOP/Package.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Conflicts.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Cookbook.pod
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Cookbook/Basics/BankAccount_MethodModifiersAndSubclassing.pod
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Cookbook/Basics/BinaryTree_AttributeFeatures.pod
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Cookbook/Basics/BinaryTree_BuilderAndLazyBuild.pod
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Cookbook/Basics/Company_Subtypes.pod
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Cookbook/Basics/DateTime_ExtendingNonMooseParent.pod
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Cookbook/Basics/Document_AugmentAndInner.pod
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Cookbook/Basics/Genome_OverloadingSubtypesAndCoercion.pod
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Cookbook/Basics/HTTP_SubtypesAndCoercion.pod
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Cookbook/Basics/Immutable.pod
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Cookbook/Basics/Person_BUILDARGSAndBUILD.pod
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Cookbook/Basics/Point_AttributesAndSubclassing.pod
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Cookbook/Extending/Debugging_BaseClassRole.pod
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Cookbook/Extending/ExtensionOverview.pod
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Cookbook/Extending/Mooseish_MooseSugar.pod
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Cookbook/Legacy/Debugging_BaseClassReplacement.pod
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Cookbook/Legacy/Labeled_AttributeMetaclass.pod
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Cookbook/Legacy/Table_ClassMetaclass.pod
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Cookbook/Meta/GlobRef_InstanceMetaclass.pod
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Cookbook/Meta/Labeled_AttributeTrait.pod
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Cookbook/Meta/PrivateOrPublic_MethodMetaclass.pod
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Cookbook/Meta/Table_MetaclassTrait.pod
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Cookbook/Meta/WhyMeta.pod
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Cookbook/Roles/ApplicationToInstance.pod
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Cookbook/Roles/Comparable_CodeReuse.pod
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Cookbook/Roles/Restartable_AdvancedComposition.pod
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Cookbook/Snack/Keywords.pod
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Cookbook/Snack/Types.pod
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Cookbook/Style.pod
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Deprecated.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/AccessorMustReadWrite.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/AddParameterizableTypeTakesParameterizableType.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/AddRoleTakesAMooseMetaRoleInstance.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/AddRoleToARoleTakesAMooseMetaRole.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/ApplyTakesABlessedInstance.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/AttachToClassNeedsAClassMOPClassInstanceOrASubclass.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/AttributeConflictInRoles.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/AttributeConflictInSummation.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/AttributeExtensionIsNotSupportedInRoles.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/AttributeIsRequired.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/AttributeMustBeAnClassMOPMixinAttributeCoreOrSubclass.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/AttributeNamesDoNotMatch.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/AttributeValueIsNotAnObject.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/AttributeValueIsNotDefined.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/AutoDeRefNeedsArrayRefOrHashRef.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/BadOptionFormat.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/BothBuilderAndDefaultAreNotAllowed.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/BuilderDoesNotExist.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/BuilderMethodNotSupportedForAttribute.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/BuilderMethodNotSupportedForInlineAttribute.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/BuilderMustBeAMethodName.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/CallingMethodOnAnImmutableInstance.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/CallingReadOnlyMethodOnAnImmutableInstance.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/CanExtendOnlyClasses.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/CanOnlyConsumeRole.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/CanOnlyWrapBlessedCode.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/CanReblessOnlyIntoASubclass.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/CanReblessOnlyIntoASuperclass.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/CannotAddAdditionalTypeCoercionsToUnion.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/CannotAddAsAnAttributeToARole.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/CannotApplyBaseClassRolesToRole.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/CannotAssignValueToReadOnlyAccessor.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/CannotAugmentIfLocalMethodPresent.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/CannotAugmentNoSuperMethod.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/CannotAutoDerefWithoutIsa.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/CannotAutoDereferenceTypeConstraint.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/CannotCalculateNativeType.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/CannotCallAnAbstractBaseMethod.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/CannotCallAnAbstractMethod.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/CannotCoerceAWeakRef.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/CannotCoerceAttributeWhichHasNoCoercion.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/CannotCreateHigherOrderTypeWithoutATypeParameter.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/CannotCreateMethodAliasLocalMethodIsPresent.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/CannotCreateMethodAliasLocalMethodIsPresentInClass.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/CannotDelegateLocalMethodIsPresent.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/CannotDelegateWithoutIsa.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/CannotFindDelegateMetaclass.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/CannotFindType.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/CannotFindTypeGivenToMatchOnType.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/CannotFixMetaclassCompatibility.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/CannotGenerateInlineConstraint.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/CannotInitializeMooseMetaRoleComposite.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/CannotInlineTypeConstraintCheck.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/CannotLocatePackageInINC.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/CannotMakeMetaclassCompatible.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/CannotOverrideALocalMethod.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/CannotOverrideBodyOfMetaMethods.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/CannotOverrideLocalMethodIsPresent.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/CannotOverrideNoSuperMethod.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/CannotRegisterUnnamedTypeConstraint.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/CannotUseLazyBuildAndDefaultSimultaneously.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/CircularReferenceInAlso.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/ClassDoesNotHaveInitMeta.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/ClassDoesTheExcludedRole.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/ClassNamesDoNotMatch.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/CloneObjectExpectsAnInstanceOfMetaclass.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/CodeBlockMustBeACodeRef.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/CoercingWithoutCoercions.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/CoercionAlreadyExists.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/CoercionNeedsTypeConstraint.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/ConflictDetectedInCheckRoleExclusions.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/ConflictDetectedInCheckRoleExclusionsInToClass.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/ConstructClassInstanceTakesPackageName.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/CouldNotCreateMethod.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/CouldNotCreateWriter.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/CouldNotEvalConstructor.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/CouldNotEvalDestructor.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/CouldNotFindTypeConstraintToCoerceFrom.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/CouldNotGenerateInlineAttributeMethod.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/CouldNotLocateTypeConstraintForUnion.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/CouldNotParseType.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/CreateMOPClassTakesArrayRefOfAttributes.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/CreateMOPClassTakesArrayRefOfSuperclasses.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/CreateMOPClassTakesHashRefOfMethods.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/CreateTakesArrayRefOfRoles.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/CreateTakesHashRefOfAttributes.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/CreateTakesHashRefOfMethods.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/DefaultToMatchOnTypeMustBeCodeRef.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/DelegationToAClassWhichIsNotLoaded.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/DelegationToARoleWhichIsNotLoaded.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/DelegationToATypeWhichIsNotAClass.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/DoesRequiresRoleName.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/EnumCalledWithAnArrayRefAndAdditionalArgs.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/EnumValuesMustBeString.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/ExtendsMissingArgs.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/HandlesMustBeAHashRef.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/IllegalInheritedOptions.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/IllegalMethodTypeToAddMethodModifier.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/IncompatibleMetaclassOfSuperclass.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/InitMetaRequiresClass.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/InitializeTakesUnBlessedPackageName.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/InstanceBlessedIntoWrongClass.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/InstanceMustBeABlessedReference.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/InvalidArgPassedToMooseUtilMetaRole.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/InvalidArgumentToMethod.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/InvalidArgumentsToTraitAliases.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/InvalidBaseTypeGivenToCreateParameterizedTypeConstraint.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/InvalidHandleValue.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/InvalidHasProvidedInARole.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/InvalidNameForType.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/InvalidOverloadOperator.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/InvalidRoleApplication.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/InvalidTypeConstraint.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/InvalidTypeGivenToCreateParameterizedTypeConstraint.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/InvalidValueForIs.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/IsaDoesNotDoTheRole.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/IsaLacksDoesMethod.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/LazyAttributeNeedsADefault.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/Legacy.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/MOPAttributeNewNeedsAttributeName.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/MatchActionMustBeACodeRef.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/MessageParameterMustBeCodeRef.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/MetaclassIsAClassNotASubclassOfGivenMetaclass.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/MetaclassIsARoleNotASubclassOfGivenMetaclass.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/MetaclassIsNotASubclassOfGivenMetaclass.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/MetaclassMustBeASubclassOfMooseMetaClass.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/MetaclassMustBeASubclassOfMooseMetaRole.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/MetaclassMustBeDerivedFromClassMOPClass.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/MetaclassNotLoaded.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/MetaclassTypeIncompatible.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/MethodExpectedAMetaclassObject.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/MethodExpectsFewerArgs.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/MethodExpectsMoreArgs.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/MethodModifierNeedsMethodName.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/MethodNameConflictInRoles.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/MethodNameNotFoundInInheritanceHierarchy.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/MethodNameNotGiven.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/MustDefineAMethodName.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/MustDefineAnAttributeName.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/MustDefineAnOverloadOperator.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/MustHaveAtLeastOneValueToEnumerate.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/MustPassAHashOfOptions.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/MustPassAMooseMetaRoleInstanceOrSubclass.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/MustPassAPackageNameOrAnExistingClassMOPPackageInstance.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/MustPassEvenNumberOfArguments.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/MustPassEvenNumberOfAttributeOptions.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/MustProvideANameForTheAttribute.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/MustSpecifyAtleastOneMethod.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/MustSpecifyAtleastOneRole.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/MustSpecifyAtleastOneRoleToApplicant.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/MustSupplyAClassMOPAttributeInstance.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/MustSupplyADelegateToMethod.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/MustSupplyAMetaclass.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/MustSupplyAMooseMetaAttributeInstance.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/MustSupplyAnAccessorTypeToConstructWith.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/MustSupplyAnAttributeToConstructWith.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/MustSupplyArrayRefAsCurriedArguments.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/MustSupplyPackageNameAndName.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/NeedsTypeConstraintUnionForTypeCoercionUnion.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/NeitherAttributeNorAttributeNameIsGiven.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/NeitherClassNorClassNameIsGiven.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/NeitherRoleNorRoleNameIsGiven.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/NeitherTypeNorTypeNameIsGiven.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/NoAttributeFoundInSuperClass.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/NoBodyToInitializeInAnAbstractBaseClass.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/NoCasesMatched.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/NoConstraintCheckForTypeConstraint.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/NoDestructorClassSpecified.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/NoImmutableTraitSpecifiedForClass.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/NoParentGivenToSubtype.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/OnlyInstancesCanBeCloned.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/OperatorIsRequired.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/OverloadConflictInSummation.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/OverloadRequiresAMetaClass.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/OverloadRequiresAMetaMethod.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/OverloadRequiresAMetaOverload.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/OverloadRequiresAMethodNameOrCoderef.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/OverloadRequiresAnOperator.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/OverloadRequiresNamesForCoderef.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/OverrideConflictInComposition.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/OverrideConflictInSummation.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/PackageDoesNotUseMooseExporter.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/PackageNameAndNameParamsNotGivenToWrap.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/PackagesAndModulesAreNotCachable.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/ParameterIsNotSubtypeOfParent.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/ReferencesAreNotAllowedAsDefault.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/RequiredAttributeLacksInitialization.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/RequiredAttributeNeedsADefault.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/RequiredMethodsImportedByClass.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/RequiredMethodsNotImplementedByClass.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/Role/Attribute.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/Role/AttributeName.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/Role/Class.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/Role/EitherAttributeOrAttributeName.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/Role/Instance.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/Role/InstanceClass.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/Role/InvalidAttributeOptions.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/Role/Method.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/Role/ParamsHash.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/Role/Role.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/Role/RoleForCreate.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/Role/RoleForCreateMOPClass.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/Role/TypeConstraint.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/RoleDoesTheExcludedRole.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/RoleExclusionConflict.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/RoleNameRequired.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/RoleNameRequiredForMooseMetaRole.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/RolesDoNotSupportAugment.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/RolesDoNotSupportExtends.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/RolesDoNotSupportInner.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/RolesDoNotSupportRegexReferencesForMethodModifiers.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/RolesInCreateTakesAnArrayRef.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/RolesListMustBeInstancesOfMooseMetaRole.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/SingleParamsToNewMustBeHashRef.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/TriggerMustBeACodeRef.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/TypeConstraintCannotBeUsedForAParameterizableType.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/TypeConstraintIsAlreadyCreated.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/TypeParameterMustBeMooseMetaType.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/UnableToCanonicalizeHandles.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/UnableToCanonicalizeNonRolePackage.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/UnableToRecognizeDelegateMetaclass.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/UndefinedHashKeysPassedToMethod.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/UnionCalledWithAnArrayRefAndAdditionalArgs.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/UnionTakesAtleastTwoTypeNames.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/ValidationFailedForInlineTypeConstraint.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/ValidationFailedForTypeConstraint.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/WrapTakesACodeRefToBless.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exception/WrongTypeConstraintGiven.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Exporter.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Intro.pod
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Manual.pod
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Manual/Attributes.pod
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Manual/BestPractices.pod
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Manual/Classes.pod
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Manual/Concepts.pod
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Manual/Construction.pod
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Manual/Contributing.pod
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Manual/Delegation.pod
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Manual/Delta.pod
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Manual/Exceptions.pod
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Manual/Exceptions/Manifest.pod
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Manual/FAQ.pod
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Manual/MOP.pod
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Manual/MethodModifiers.pod
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Manual/MooseX.pod
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Manual/Resources.pod
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Manual/Roles.pod
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Manual/Support.pod
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Manual/Types.pod
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Manual/Unsweetened.pod
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Meta/Attribute.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Meta/Attribute/Native.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Meta/Attribute/Native/Trait.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Meta/Attribute/Native/Trait/Array.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Meta/Attribute/Native/Trait/Bool.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Meta/Attribute/Native/Trait/Code.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Meta/Attribute/Native/Trait/Counter.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Meta/Attribute/Native/Trait/Hash.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Meta/Attribute/Native/Trait/Number.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Meta/Attribute/Native/Trait/String.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Meta/Class.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Meta/Class/Immutable/Trait.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Meta/Instance.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Meta/Method.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Meta/Method/Accessor.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Meta/Method/Accessor/Native.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Meta/Method/Accessor/Native/Array.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Meta/Method/Accessor/Native/Array/Writer.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Meta/Method/Accessor/Native/Array/accessor.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Meta/Method/Accessor/Native/Array/clear.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Meta/Method/Accessor/Native/Array/count.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Meta/Method/Accessor/Native/Array/delete.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Meta/Method/Accessor/Native/Array/elements.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Meta/Method/Accessor/Native/Array/first.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Meta/Method/Accessor/Native/Array/first_index.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Meta/Method/Accessor/Native/Array/get.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Meta/Method/Accessor/Native/Array/grep.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Meta/Method/Accessor/Native/Array/insert.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Meta/Method/Accessor/Native/Array/is_empty.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Meta/Method/Accessor/Native/Array/join.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Meta/Method/Accessor/Native/Array/map.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Meta/Method/Accessor/Native/Array/natatime.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Meta/Method/Accessor/Native/Array/pop.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Meta/Method/Accessor/Native/Array/push.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Meta/Method/Accessor/Native/Array/reduce.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Meta/Method/Accessor/Native/Array/set.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Meta/Method/Accessor/Native/Array/shallow_clone.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Meta/Method/Accessor/Native/Array/shift.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Meta/Method/Accessor/Native/Array/shuffle.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Meta/Method/Accessor/Native/Array/sort.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Meta/Method/Accessor/Native/Array/sort_in_place.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Meta/Method/Accessor/Native/Array/splice.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Meta/Method/Accessor/Native/Array/uniq.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Meta/Method/Accessor/Native/Array/unshift.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Meta/Method/Accessor/Native/Bool/not.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Meta/Method/Accessor/Native/Bool/set.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Meta/Method/Accessor/Native/Bool/toggle.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Meta/Method/Accessor/Native/Bool/unset.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Meta/Method/Accessor/Native/Code/execute.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Meta/Method/Accessor/Native/Code/execute_method.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Meta/Method/Accessor/Native/Collection.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Meta/Method/Accessor/Native/Counter/Writer.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Meta/Method/Accessor/Native/Counter/dec.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Meta/Method/Accessor/Native/Counter/inc.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Meta/Method/Accessor/Native/Counter/reset.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Meta/Method/Accessor/Native/Counter/set.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Meta/Method/Accessor/Native/Hash.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Meta/Method/Accessor/Native/Hash/Writer.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Meta/Method/Accessor/Native/Hash/accessor.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Meta/Method/Accessor/Native/Hash/clear.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Meta/Method/Accessor/Native/Hash/count.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Meta/Method/Accessor/Native/Hash/defined.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Meta/Method/Accessor/Native/Hash/delete.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Meta/Method/Accessor/Native/Hash/elements.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Meta/Method/Accessor/Native/Hash/exists.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Meta/Method/Accessor/Native/Hash/get.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Meta/Method/Accessor/Native/Hash/is_empty.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Meta/Method/Accessor/Native/Hash/keys.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Meta/Method/Accessor/Native/Hash/kv.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Meta/Method/Accessor/Native/Hash/set.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Meta/Method/Accessor/Native/Hash/shallow_clone.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Meta/Method/Accessor/Native/Hash/values.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Meta/Method/Accessor/Native/Number/abs.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Meta/Method/Accessor/Native/Number/add.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Meta/Method/Accessor/Native/Number/div.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Meta/Method/Accessor/Native/Number/mod.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Meta/Method/Accessor/Native/Number/mul.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Meta/Method/Accessor/Native/Number/set.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Meta/Method/Accessor/Native/Number/sub.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Meta/Method/Accessor/Native/Reader.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Meta/Method/Accessor/Native/String/append.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Meta/Method/Accessor/Native/String/chomp.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Meta/Method/Accessor/Native/String/chop.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Meta/Method/Accessor/Native/String/clear.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Meta/Method/Accessor/Native/String/inc.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Meta/Method/Accessor/Native/String/length.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Meta/Method/Accessor/Native/String/match.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Meta/Method/Accessor/Native/String/prepend.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Meta/Method/Accessor/Native/String/replace.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Meta/Method/Accessor/Native/String/substr.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Meta/Method/Accessor/Native/Writer.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Meta/Method/Augmented.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Meta/Method/Constructor.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Meta/Method/Delegation.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Meta/Method/Destructor.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Meta/Method/Meta.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Meta/Method/Overridden.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Meta/Mixin/AttributeCore.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Meta/Object/Trait.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Meta/Role.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Meta/Role/Application.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Meta/Role/Application/RoleSummation.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Meta/Role/Application/ToClass.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Meta/Role/Application/ToInstance.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Meta/Role/Application/ToRole.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Meta/Role/Attribute.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Meta/Role/Composite.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Meta/Role/Method.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Meta/Role/Method/Conflicting.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Meta/Role/Method/Required.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Meta/TypeCoercion.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Meta/TypeCoercion/Union.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Meta/TypeConstraint.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Meta/TypeConstraint/Class.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Meta/TypeConstraint/DuckType.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Meta/TypeConstraint/Enum.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Meta/TypeConstraint/Parameterizable.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Meta/TypeConstraint/Parameterized.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Meta/TypeConstraint/Registry.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Meta/TypeConstraint/Role.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Meta/TypeConstraint/Union.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Object.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Role.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Spec/Role.pod
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Unsweetened.pod
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Util.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Util/MetaRole.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Util/TypeConstraints.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Moose/Util/TypeConstraints/Builtins.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/Test/Moose.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/metaclass.pm
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/oose.pm

%files bin
%defattr(-,root,root,-)
/usr/bin/moose-outdated

%files dev
%defattr(-,root,root,-)
/usr/share/man/man3/Class::MOP.3
/usr/share/man/man3/Class::MOP::Attribute.3
/usr/share/man/man3/Class::MOP::Class.3
/usr/share/man/man3/Class::MOP::Class::Immutable::Trait.3
/usr/share/man/man3/Class::MOP::Deprecated.3
/usr/share/man/man3/Class::MOP::Instance.3
/usr/share/man/man3/Class::MOP::Method.3
/usr/share/man/man3/Class::MOP::Method::Accessor.3
/usr/share/man/man3/Class::MOP::Method::Constructor.3
/usr/share/man/man3/Class::MOP::Method::Generated.3
/usr/share/man/man3/Class::MOP::Method::Inlined.3
/usr/share/man/man3/Class::MOP::Method::Meta.3
/usr/share/man/man3/Class::MOP::Method::Wrapped.3
/usr/share/man/man3/Class::MOP::MiniTrait.3
/usr/share/man/man3/Class::MOP::Mixin.3
/usr/share/man/man3/Class::MOP::Mixin::AttributeCore.3
/usr/share/man/man3/Class::MOP::Mixin::HasAttributes.3
/usr/share/man/man3/Class::MOP::Mixin::HasMethods.3
/usr/share/man/man3/Class::MOP::Mixin::HasOverloads.3
/usr/share/man/man3/Class::MOP::Module.3
/usr/share/man/man3/Class::MOP::Object.3
/usr/share/man/man3/Class::MOP::Overload.3
/usr/share/man/man3/Class::MOP::Package.3
/usr/share/man/man3/Moose.3
/usr/share/man/man3/Moose::Cookbook.3
/usr/share/man/man3/Moose::Cookbook::Basics::BankAccount_MethodModifiersAndSubclassing.3
/usr/share/man/man3/Moose::Cookbook::Basics::BinaryTree_AttributeFeatures.3
/usr/share/man/man3/Moose::Cookbook::Basics::BinaryTree_BuilderAndLazyBuild.3
/usr/share/man/man3/Moose::Cookbook::Basics::Company_Subtypes.3
/usr/share/man/man3/Moose::Cookbook::Basics::DateTime_ExtendingNonMooseParent.3
/usr/share/man/man3/Moose::Cookbook::Basics::Document_AugmentAndInner.3
/usr/share/man/man3/Moose::Cookbook::Basics::Genome_OverloadingSubtypesAndCoercion.3
/usr/share/man/man3/Moose::Cookbook::Basics::HTTP_SubtypesAndCoercion.3
/usr/share/man/man3/Moose::Cookbook::Basics::Immutable.3
/usr/share/man/man3/Moose::Cookbook::Basics::Person_BUILDARGSAndBUILD.3
/usr/share/man/man3/Moose::Cookbook::Basics::Point_AttributesAndSubclassing.3
/usr/share/man/man3/Moose::Cookbook::Extending::Debugging_BaseClassRole.3
/usr/share/man/man3/Moose::Cookbook::Extending::ExtensionOverview.3
/usr/share/man/man3/Moose::Cookbook::Extending::Mooseish_MooseSugar.3
/usr/share/man/man3/Moose::Cookbook::Legacy::Debugging_BaseClassReplacement.3
/usr/share/man/man3/Moose::Cookbook::Legacy::Labeled_AttributeMetaclass.3
/usr/share/man/man3/Moose::Cookbook::Legacy::Table_ClassMetaclass.3
/usr/share/man/man3/Moose::Cookbook::Meta::GlobRef_InstanceMetaclass.3
/usr/share/man/man3/Moose::Cookbook::Meta::Labeled_AttributeTrait.3
/usr/share/man/man3/Moose::Cookbook::Meta::PrivateOrPublic_MethodMetaclass.3
/usr/share/man/man3/Moose::Cookbook::Meta::Table_MetaclassTrait.3
/usr/share/man/man3/Moose::Cookbook::Meta::WhyMeta.3
/usr/share/man/man3/Moose::Cookbook::Roles::ApplicationToInstance.3
/usr/share/man/man3/Moose::Cookbook::Roles::Comparable_CodeReuse.3
/usr/share/man/man3/Moose::Cookbook::Roles::Restartable_AdvancedComposition.3
/usr/share/man/man3/Moose::Cookbook::Snack::Keywords.3
/usr/share/man/man3/Moose::Cookbook::Snack::Types.3
/usr/share/man/man3/Moose::Cookbook::Style.3
/usr/share/man/man3/Moose::Deprecated.3
/usr/share/man/man3/Moose::Exception.3
/usr/share/man/man3/Moose::Exporter.3
/usr/share/man/man3/Moose::Intro.3
/usr/share/man/man3/Moose::Manual.3
/usr/share/man/man3/Moose::Manual::Attributes.3
/usr/share/man/man3/Moose::Manual::BestPractices.3
/usr/share/man/man3/Moose::Manual::Classes.3
/usr/share/man/man3/Moose::Manual::Concepts.3
/usr/share/man/man3/Moose::Manual::Construction.3
/usr/share/man/man3/Moose::Manual::Contributing.3
/usr/share/man/man3/Moose::Manual::Delegation.3
/usr/share/man/man3/Moose::Manual::Delta.3
/usr/share/man/man3/Moose::Manual::Exceptions.3
/usr/share/man/man3/Moose::Manual::Exceptions::Manifest.3
/usr/share/man/man3/Moose::Manual::FAQ.3
/usr/share/man/man3/Moose::Manual::MOP.3
/usr/share/man/man3/Moose::Manual::MethodModifiers.3
/usr/share/man/man3/Moose::Manual::MooseX.3
/usr/share/man/man3/Moose::Manual::Resources.3
/usr/share/man/man3/Moose::Manual::Roles.3
/usr/share/man/man3/Moose::Manual::Support.3
/usr/share/man/man3/Moose::Manual::Types.3
/usr/share/man/man3/Moose::Manual::Unsweetened.3
/usr/share/man/man3/Moose::Meta::Attribute.3
/usr/share/man/man3/Moose::Meta::Attribute::Native.3
/usr/share/man/man3/Moose::Meta::Attribute::Native::Trait.3
/usr/share/man/man3/Moose::Meta::Attribute::Native::Trait::Array.3
/usr/share/man/man3/Moose::Meta::Attribute::Native::Trait::Bool.3
/usr/share/man/man3/Moose::Meta::Attribute::Native::Trait::Code.3
/usr/share/man/man3/Moose::Meta::Attribute::Native::Trait::Counter.3
/usr/share/man/man3/Moose::Meta::Attribute::Native::Trait::Hash.3
/usr/share/man/man3/Moose::Meta::Attribute::Native::Trait::Number.3
/usr/share/man/man3/Moose::Meta::Attribute::Native::Trait::String.3
/usr/share/man/man3/Moose::Meta::Class.3
/usr/share/man/man3/Moose::Meta::Class::Immutable::Trait.3
/usr/share/man/man3/Moose::Meta::Instance.3
/usr/share/man/man3/Moose::Meta::Method.3
/usr/share/man/man3/Moose::Meta::Method::Accessor.3
/usr/share/man/man3/Moose::Meta::Method::Augmented.3
/usr/share/man/man3/Moose::Meta::Method::Constructor.3
/usr/share/man/man3/Moose::Meta::Method::Delegation.3
/usr/share/man/man3/Moose::Meta::Method::Destructor.3
/usr/share/man/man3/Moose::Meta::Method::Meta.3
/usr/share/man/man3/Moose::Meta::Method::Overridden.3
/usr/share/man/man3/Moose::Meta::Mixin::AttributeCore.3
/usr/share/man/man3/Moose::Meta::Object::Trait.3
/usr/share/man/man3/Moose::Meta::Role.3
/usr/share/man/man3/Moose::Meta::Role::Application.3
/usr/share/man/man3/Moose::Meta::Role::Application::RoleSummation.3
/usr/share/man/man3/Moose::Meta::Role::Application::ToClass.3
/usr/share/man/man3/Moose::Meta::Role::Application::ToInstance.3
/usr/share/man/man3/Moose::Meta::Role::Application::ToRole.3
/usr/share/man/man3/Moose::Meta::Role::Attribute.3
/usr/share/man/man3/Moose::Meta::Role::Composite.3
/usr/share/man/man3/Moose::Meta::Role::Method.3
/usr/share/man/man3/Moose::Meta::Role::Method::Conflicting.3
/usr/share/man/man3/Moose::Meta::Role::Method::Required.3
/usr/share/man/man3/Moose::Meta::TypeCoercion.3
/usr/share/man/man3/Moose::Meta::TypeCoercion::Union.3
/usr/share/man/man3/Moose::Meta::TypeConstraint.3
/usr/share/man/man3/Moose::Meta::TypeConstraint::Class.3
/usr/share/man/man3/Moose::Meta::TypeConstraint::DuckType.3
/usr/share/man/man3/Moose::Meta::TypeConstraint::Enum.3
/usr/share/man/man3/Moose::Meta::TypeConstraint::Parameterizable.3
/usr/share/man/man3/Moose::Meta::TypeConstraint::Parameterized.3
/usr/share/man/man3/Moose::Meta::TypeConstraint::Registry.3
/usr/share/man/man3/Moose::Meta::TypeConstraint::Role.3
/usr/share/man/man3/Moose::Meta::TypeConstraint::Union.3
/usr/share/man/man3/Moose::Object.3
/usr/share/man/man3/Moose::Role.3
/usr/share/man/man3/Moose::Spec::Role.3
/usr/share/man/man3/Moose::Unsweetened.3
/usr/share/man/man3/Moose::Util.3
/usr/share/man/man3/Moose::Util::MetaRole.3
/usr/share/man/man3/Moose::Util::TypeConstraints.3
/usr/share/man/man3/Moose::Util::TypeConstraints::Builtins.3
/usr/share/man/man3/Test::Moose.3
/usr/share/man/man3/metaclass.3
/usr/share/man/man3/oose.3

%files lib
%defattr(-,root,root,-)
/usr/lib/perl5/vendor_perl/5.28.1x86_64-linux-thread-multi/auto/Moose/Moose.so
